### PR TITLE
[bug] npm install always installs express@3.10.5

### PR DESCRIPTION
**Pull request by koulmomo**
installing the latest version of [`arrow`](http://github.com/yahoo/arrow) has [`express@4.x`](https://github.com/yahoo/arrow/blob/524bbcae35b3f680a6ee38c910d67aa0fae8fcbb/package.json#L47) listed as a dependency.

However, it also has a [`shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) file which lists [`express@3.10.5`](https://github.com/yahoo/arrow/blob/524bbcae35b3f680a6ee38c910d67aa0fae8fcbb/npm-shrinkwrap.json#L88).

Because of this, running `npm install` always installs `express@3.10.5`

There are two possible fixes for this
1) :fire: npm-shrinkwrap and make sure it is never checked in (this is what this PR does)
2) generate a new npm-shrinkwrap with the proper deps + devDeps, also adding a precommit-hook that makes sure to generate a new shrinkwrap per commit so this doesn't happen again

cc @akshayp

### CODE REVIEW

**Comment by pranavparikh** [comment]
@koulmomo ,
Thanks for the PR. I fixed it with 0.6.14. Didn't notice that unit tests failed. Looking into it.

**Comment by koulmomo** [comment]
@pranavparikh is there a reason why you are committing a shrinkwrap? There is a lot of possibility for human error this way.

**Comment by pranavparikh** [comment]
@koulmomo ,
We should not committing the shrinkwrap. But long time ago, one of the downstream package upgrade caused issues. So started committing shrinkwrap to lock down the dependencies to avoid such issues.

**Comment by akshayp** [comment]
@pranavparikh The shrinkwrap also prevents common modules from being hoisted up and make yahoo arrow very large. Since the issue with the downstream package has been fixed. Can we publish a version without a shrinkwrap? It should reduce the size of this package by quite a bit

**Comment by pranavparikh** [comment]
@koulmomo ,
The issue with Express upgrade should be fixed with the latest version. Please check and confirm. 

@akshayp ,
Removing shrinkwrap makes sense. I'll remove it in next release. Tracking it here - https://github.com/yahoo/arrow/issues/292

**Pull request closed without merging**
